### ISSUE TITLE
Bar status should blink if the bar closed less then 3min ago

### ISSUE THREAD

**Issue by ij0n** [c-base/infoscreens#10]
Like the physical status indicators

**Comment by bergie** [comment]
I suppose we could do these fall all the status indicators (replicator, c_nancy, etc) to make the status change more visible

**Comment by bergie** [comment]
Note: now we switch screens once per minute, so this will require adding the timestamp to the OpenMCT back-end, since the web page is unlikely to remain in memory for 3min

**Comment by bergie** [comment]
Now we know the latest time the value changed by adding `?timestamp=true` to the URL

Example:

http://openmct.cbrp3.c-base.org/telemetry/latest/bar.open?timestamp=true
